{{- range $apps, $app := .Values.applications }}
{{- range $env := $app.environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.appName }}-{{ $env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    repoURL: https://github.com/philkrause/helm-charts.git
    targetRevision: {{ $env }}
    path: {{ $app.appName }}
    helm:
      valueFiles:
        - values-{{ $env }}.yaml
  destination:
    namespace: {{ $app.namespace }}
    server: "https://kubernetes.default.svc"
{{- end }}
{{- end }}