{{- range $apps, $app := .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
spec:
  project: default 
  source:
    repoURL: https://github.com/philkrause/helm-charts.git
    targetRevision: {{ $app.targetRevision }}
    path: {{ $app.chartName }}
    helm:
      valueFiles:
        - {{ $app.chartName }}/values-dev.yaml
  destination:
    namespace: {{ $app.namespace }}
    server: "https://kubernetes.default.svc"
{{- end }}