{{- range $appIndex, $app := .Values.applications }}
{{- range $envIndex, $env := .environments }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.appName }}-{{ $env }}
spec:
  project: default 
  source:
    repoURL: https://github.com/philkrause/helm-charts.git
    targetRevision: {{ $env }}
    path: {{ $app.chartName }}
    helm:
      valueFiles:
        - {{ $app.chartName }}/values-{{ $env }}.yaml
  destination:
    namespace: {{ $app.namespace }}
    server: "https://kubernetes.default.svc"
{{- end }}
{{- end }}
