{{- range $apps, $app := .Values.applications }}
{{- range $environments, $env := .environments }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.appName }}-{{ . }}
  namespace: {{ $app.namespace }}}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    repoURL: https://github.com/philkrause/helm-charts.git
    targetRevision: {{ . }}
    chart: {{ $app.appName }}
    path: {{ $app.appName }}
    helm:
      valueFiles:
        - hello-world/values-{{ . }}.yaml
  destination:
    namespace: {{ $app.namespace }}
    server: "https://kubernetes.default.svc"
{{- end }}
{{- end }}