{{- range $apps, $app := .Values.applications }}
{{- range $environments, $env := .environments }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .appName }}-{{ . }}
spec:
  project: default 
  source:
    repoURL: https://github.com/philkrause/helm-charts.git
    targetRevision: {{ . }}
    path: {{ .chartName }}
    helm:
      valueFiles:
        - {{ .chartName }}/values-{{ . }}.yaml
  destination:
    namespace: {{ .namespace }}
    server: "https://kubernetes.default.svc"
{{- end }}
{{- end }}