{{- range .Values.applications }}
{{- $appName := .appName }}
{{- $namespace := .namespace }}
{{- $targetRevision := .targetRevision }}
{{- $chartName := .chartName }}
{{- $range .environments }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}-{{ . }}
spec:
  project: deathstar-argocd-project 
  source:
    repoURL: https://github.com/philkrause/helm-charts.git
    targetRevision: {{ $targetRevision }}
    path: {{ $chartName }}
    helm:
      valueFiles:
        - {{ $chartName }}/values-{{ . }}.yaml
  destination:
    namespace: {{ $namespace }}
    server: "https://kubernetes.default.svc"
{{- end }}
{{- end }}