default:
  path: "clusters/dev/apps"
applications:
  - namespace: applications
    path: "clusters/dev/apps"
    charts:
      - name: hello-world
  - namespace: valheim
    path: "clusters/dev/apps"
    charts:
      - name: valheim