{{- range $namespace, $nVal := concat .Values.applications .Values.additionalApplications }}
{{- range $name, $val := $nVal.charts }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $val.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $nVal.namespace | default $val.name }}
    server: {{ $val.server | default $.Values.default.app.destination.server | required (printf "No destination.server specified for %s" $val.name ) }}
  project: {{ $val.project | default $.Values.default.app.project | required (printf "No project specified for %s" $val.name ) }}
  sources:
    - repoURL: {{ $val.repoURL | default $.Values.default.app.source.repoURL }}
      {{- if $val.chart }}
      chart: {{ $val.chart }}
      {{- else }}
      path: {{ $val.path | default (printf "%s/%s%s" $.Values.default.path ($nVal.path | default "") $val.name)}}
      {{- end }}
      {{- if $val.ref }}
      ref: {{ $val.ref }}
      {{- end }}
      targetRevision: {{ $val.targetRevision | default $.Values.default.app.source.targetRevision }}
      helm:
        passCredentials: true

{{- if $val.ignore }}
  ignoreDifferences:
{{ $val.ignore | toYaml | indent 4 }}
{{- end }}

  revisionHistoryLimit: {{ $val.revisionHistoryLimit | default $.Values.default.app.revisionHistoryLimit }}

  syncPolicy:
{{- if $val.syncPolicy  }}
{{- if $val.syncPolicy.automated }}
    automated:
{{ $val.syncPolicy.automated | toYaml | indent 6 }}
{{- end }}
{{- else }}
    automated:
{{ $.Values.default.app.syncPolicy.automated | toYaml | indent 6 }}
{{- end }}
    syncOptions:
      - CreateNamespace=true
{{- if $val.replace | default $.Values.default.app.syncOptions.replace }}
      - Replace=true
{{- end }}
{{- if $val.pruneLast | default $.Values.default.app.syncOptions.pruneLast }}
      - PruneLast=true
{{- end }}
{{- if $val.applyOutOfSyncOnly | default $.Values.default.app.syncOptions.applyOutOfSyncOnly }}
      - ApplyOutOfSyncOnly=true
{{- end }}
{{- if $val.skipValidate | default $.Values.default.app.syncOptions.skipValidate }}
      - Validate=false
{{- end }}
{{- if $val.ignore  }}
      - RespectIgnoreDifferences=true
{{- end }}
{{- if $val.serverApply | default $.Values.default.app.syncOptions.serverApply }}
      - ServerSideApply=true
{{- end }}
{{- if $val.syncPolicy }}
{{- if $val.syncPolicy.retry }}
    retry:
{{ $val.syncPolicy.retry | toYaml | indent 6 }}
{{- end }}
{{- else }}
    retry:
{{ $.Values.default.app.syncPolicy.retry | toYaml | indent 6 }}
{{- end }}


{{- end }}

{{- end }}
